version: '2'

#代码目录请在.env 文件中配置
services:
  ecstore:
    image: 'wykrisdev/shopex-docker:php72-swooleloader'
    container_name: bbc-base
    ports:
      - 80:80
    volumes:
      #本地路径/远程路径
      - ${coderoot}:/data/httpd
    links:
      - mysql
      - redis
      - ftp
    environment:
      #默认web的路径
      - WEBROOT="${webroot}"
      #默认zl文件的路径
      - LICENSE_PATH="${license_path}"
    networks:
      - bbc

  redis:
    image: redis
    hostname: redis
    container_name: bbc-redis
    ports:
      - "6379:6379"
    volumes:
      - ${storage_path}/redis:/data
    networks:
      - bbc

  mysql:
    image: mysql:5.6
    hostname: mysql
    container_name: bbc-mysql
    ports:
      - "3306:3306"
    volumes:
      - ${storage_path}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - bbc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8004:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - bbc

  ftp:
    image: bogem/ftp
    hostname: ftp
    container_name: ftp
    environment:
      - FTP_USER=ftp
      - FTP_PASS=ftp
      - PASV_ADDRESS=0.0.0.0
    volumes:
      - ${storage_path}/ftp:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    networks:
       - bbc

networks:
  bbc:
    driver: bridge
